import "./globals.css";
import { Inter } from "next/font/google";
import { DM_Sans } from "next/font/google";
import { AuthContextProvider } from "./context/AuthContext";

const inter = Inter({ subsets: ["latin"] });
const dmsans = DM_Sans({
  weight: ["500", "400"],
  subsets: ["latin"],
  variable: "--font-dmsans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${dmsans.variable}`}>
        <AuthContextProvider>{children}</AuthContextProvider>
      </body>
    </html>
  );
}
